### ISSUE TITLE
Display drop area only on drag enter.

### ISSUE THREAD

**Issue by topless** [danialfarid/angular-file-upload#360]
This might not really be an issue but I am struggling for some hours now to achieve the desired effect.
I would like to designate `body` as the drop-area and then display a custom overlay which covers all screen.  In your Demo there is already a predefined div where you apply your drop-area class but in my case I would like to just display that  on `dragenter` and hide it on `dragleave`.  Do you have any suggestions for that? Great work by the way.

**Comment by danialfarid** [comment]
You can use drag-over-class option to set the class when the file is dragged over. that class can make your element look like drop box, if you haven't figured it out yet.

**Comment by RanzQ** [comment]
@topless I did this by putting the drop directive to body, then body gets the drag classes. Then just create css selectors so that you toggle `display: none / block;` for your drop-area div, which should fill the whole screen. Like this with LESS:

```
.drop-layer {
  background-color: fade(black, 0%);
  position: fixed;
  left: 0;
  top: 0;
  right: auto;
  bottom: auto;
  width: 100%;
  height: 100%;
  display: none;
  z-index: @zindex-modal;
}

.dragover-valid, .dragover-invalid {
  .drop-layer {
    background-color: fade(black, 30%);
    display: block;
  }
}
```
