### ISSUE TITLE
Authorization Header seems to be not send or something

### ISSUE THREAD

**Issue by Kageetai** [danialfarid/angular-file-upload#407]
Hi there,

I am trying to upload an image to imgur with this code which I derived from #88 but I always get `403 (Permission Denied)`

Here is my code in the controller so far:
```
$scope.onFileSelect = function (files) {
      var fileReader = new FileReader();
      fileReader.readAsArrayBuffer(files[0]);
      fileReader.onload = function (e) {
        $upload.http({
          url: 'https://api.imgur.com/3/image',
          //method: 'POST',
          headers: {
            'Authorization': 'Client-ID XXXXXXXXXXXXXX',
            'Content-Type': files[0].type
          },
          data: e.target.result
        }).then(function (response) {
          console.log(data);
        }, null, function (evt) {
          //$scope.progress[index] = parseInt(100.0 * evt.loaded / evt.total);
          console.log(parseInt(100.0 * evt.loaded / evt.total));
        });
      };
    };
```

And here a screenshot of the request in the Chrome network panel. I noticed the authorization header is different there.
![capture](https://cloud.githubusercontent.com/assets/1738309/5049052/60892868-6c1a-11e4-93f3-798d0982ab18.PNG)

**Comment by danialfarid** [comment]
If you could create a jsfiddle to show the error I can investigate more, you can reopen the issue if you do.
