### ISSUE TITLE
fileupload not working in IE, not hitting the backend

### ISSUE THREAD

**Issue by satishmukku** [danialfarid/angular-file-upload#409]
Hi 

I am using angular-file-upload for my app, everything working fine in chrome and firefox, but I am getting the problem with IE,

Its not even hitting the server at all, Can u help me to find out the bug
![fileuploadie](https://cloud.githubusercontent.com/assets/4066253/5088190/e96a6e50-6f56-11e4-961a-5fa1d5128d3a.png)

Working fine in Chrome
![chrome](https://cloud.githubusercontent.com/assets/4066253/5088250/6d8c02d4-6f57-11e4-86bd-f8d9f23db335.png)

**Comment by stephendiadamo** [comment]
Any update on this issue? Having the same problem.

**Comment by satishmukku** [comment]
@stephendiadamo angular-file-upload doesn't support custom headers, so its not sending any provision headers,

I made lot of changes to backend according to it, but still facing the issue, its working absolutely fine in Non IE browsers
