### ISSUE TITLE
Has an error in FireFox browser

### ISSUE THREAD

**Issue by cbunhok** [danialfarid/angular-file-upload#412]
Hello Mr. @danialfarid,

I got an error using this library in FireFox browser.
Here is the error:
"Error: Argument 2 of FormData.append does not implement interface Blob.
this.upload/b.transformRequest@http://localhost:3000/assets/ng-file-upload/angular-file-upload.min.js?body=1:3:1910
Vc@http://localhost:3000/assets/angular/angular.min.js?body=1:77:1
l/f<@http://localhost:3000/assets/angular/angular.min.js?body=1:80:121
f/<@http://localhost:3000/assets/angular/angular.min.js?body=1:111:390
Me/this.$get</k.prototype.$eval@http://localhost:3000/assets/angular/angular.min.js?body=1:125:246
Me/this.$get</k.prototype.$digest@http://localhost:3000/assets/angular/angular.min.js?body=1:122:324
Me/this.$get</k.prototype.$apply@http://localhost:3000/assets/angular/angular.min.js?body=1:126:10
Bc[c]</<.compile/</<@http://localhost:3000/assets/angular/angular.min.js?body=1:227:245
n.event.dispatch@http://localhost:3000/assets/jquery/dist/jquery.min.js?body=1:4:6352
n.event.add/r.handle@http://localhost:3000/assets/jquery/dist/jquery.min.js?body=1:4:3162

Do you have any solution about this?

Thanks

**Comment by wesrice** [comment]
@danialfarid - For what it's worth, I get this in Firefox as well under the following conditions:
* The file input is optional
* The user chooses not to populate the file input
* The form is submitted

**Comment by danialfarid** [comment]
What do you mean user chooses not to populate the file input?
Could you create a jsfiddle showing this error?

**Comment by ikhattab** [comment]
@wesrice initialize file value with `null` solved this issue for me for example:
```javascript
...
// I'm using it to upload single file and store it in $scope.attachment
// and I just initialize it with null
$scope.attachment = null;
```
many areas of code check for `null` value explicitly. I don't have much time now to trace which one causes but this solves my problem for now. hope it helps

**Comment by labham** [comment]
I faced the same issue. Following is the piece of code:

HTML:
<div multiple="multiple" ng-file-drag-over-class="optional-css-class" ng-file-drop="addFile($file)">
</div>

JS:
function addFile(file){
	   var fileOrig = file;
           var fileCopy = angular.copy(file);
 };

The variable fileOrig points directly to the file object, that I selected for upload ( or whatever). It works fine for me while upload.
But if I try to upload fileCopy, it will throw the above-stated error. It only has the attributes copied, but loses reference to original selected file.

So I guess it is an issue of reference / copy of object.

Hope this helps.

**Comment by labham** [comment]
I faced the same issue. Following is the piece of code:

HTML:
<div ng-file-drop="addFile($file)" ng-file-drag-over-class="optional-css-class" multiple="multiple"></div>

JS:
function addFile(file){
var fileOrig = file;
var fileCopy = angular.copy(file);
};

The variable fileOrig points directly to the file object, that I selected for upload ( or whatever). It works fine for me while upload.
But if I try to upload fileCopy, it will throw the above-stated error. It only has the attributes copied, but loses reference to original selected file.

So I guess it is an issue of reference / copy of object.

Hope this helps.

**Comment by labham** [comment]
I faced the same issue. Following is the piece of code:
  
JS:
function addFile(file){
var fileOrig = file;
var fileCopy = angular.copy(file);
};

The variable fileOrig points directly to the file object, that I selected for upload ( or whatever). It works fine for me while upload.
But if I try to upload fileCopy, it will throw the above-stated error. It only has the attributes copied, but loses reference to original selected file.

So I guess it is an issue of reference / copy of object.

Hope this helps.

**Comment by bzitzow** [comment]
FWIW: I received this error when running jasmine specs via karma setting an expectation on what Upload.upload() should receive. 

The cause: 
```javascript
$scope.files = ['Im a pretend file for specs'];
```

The fix:
```javascript
var testFile = new Blob(['Im a pretend file for specs']);
$scope.files = [testFile];
```

**Comment by kishor10d** [comment]
I am facing same issue.
```javascript
Error: Argument 2 of FormData.append is not an object.
```

I am generating the 2 or more forms dynamically and binding that HTML by using directive to main view.

ex. 
```javascript
$compile("<input type='file' ngf-select />")(scope);
```

When I am using normal file upload, it works fine.
But when generate the HTML dynamically, Its not working at all..
Not working means file not uploding if I set the model to "null"...
and if not set to null then error above stated error occurs.


The plunker is created here
[PLUNKER](http://plnkr.co/edit/S7hnVJnuDjWUMQ6PYewk?p=preview)

The above error not appearing in CHROME and file not uploading; error comes in firefox and after error nothing will happen. If the model set to null then file will not uploading..

Is there any solution for this???

**Comment by danialfarid** [comment]
Your plunker doesn't seem to work, I get `ReferenceError: Upload is not defined` error

**Comment by kishor10d** [comment]
I got the same error when I am trying like this.

Upload.upload({
			url : BASE_URL + 'registerVolunteer',
			fields : { 'companyName' : $scope.volData.companyName, 'actionCatId': $scope.volData.actionCats.actionCatId,
						'userEmail' : $base64.encode($scope.volData.userEmail),'password' : $base64.encode($scope.volData.password),
						'address': $scope.volData.address, 'description' :$scope.volData.description,
						'irsBranch': $scope.volData.irsBranch, 'vatNo' : $scope.volData.vatNo, 'someId' : $scope.volData.someId,
						'bankAccount':$scope.volData.bankAccount},
			file :  [ $scope.volData.photo, $scope.volData.media]
		}).success(function (data, status, headers, config) {
			
        });

I have 2 file upload controls in my form, to upload two separate files.

**Comment by gajdot** [comment]
Same error... Why is this closed?
