### ISSUE TITLE
IE9 Issue during the file upload

### ISSUE THREAD

**Issue by surendharrudra** [danialfarid/angular-file-upload#429]
On IE9, file is uploaded property to server & getting response back from server. But, browser fail to handle response.

I have tried to debug the issue with non-minified version of files & observed that “xhr.status” is throwing below error in (angular.js). However other HTTP POST requests are working fine in IE9.
SCRIPT575: Could not complete the operation due to error c00c023f.

HTML configuration:
<script src="vendor/fileUpload/FileAPI.js" type="text/javascript"></script>
<script src="vendor/fileUpload/angular-file-upload-shim.js" type="text/javascript"></script>
<script src="vendor/angular.js" type="text/javascript"></script>
<script src="vendor/fileUpload/angular-file-upload.js" type="text/javascript"></script>
<script src="vendor/angular-route.js" type="text/javascript"></script>

Angular Controller:
$scope.upload = $upload.upload({
	url: '/myts/rs/hr/compensationAnalysis/upload',
        method: 'POST',
        headers: {"Access-Control-Allow-Origin":"*", "Access-Control-Allow-Headers":"X-Requested-With"},
        file: file
}).success(function(data, status, headers, config) {
	//TODO: Handle success
}).error(function(data, status, headers, config){
	//TODO: handle error
});

Versions:
1. angular.JS : 1.2.27
2. angular-file-upload.js & angular-file-upload-shim.js : 1.6.12
3. FileAPI.js – 2.0.7

Can you please help me out in fixing this issue. 

Many thanks in advance.

Regards,
Surendhar

**Comment by danialfarid** [comment]
If this works on demo page, it is the way you are configuring using the plugin that makes it break, So if you could create a jsfiddle or post mini version of your code here I can investigate more. Otherwise the plugin should work if you configure it as it is configured in the demo page.
