### ISSUE TITLE
progress() and success() are wonky in Firefox

### ISSUE THREAD

**Issue by izeau** [danialfarid/angular-file-upload#438]
Sometimes, the progress “rolls back”: it goes up and back to 0, then tries to upload again, then goes back to 0, etc.

The `success` event is not fired, even when progress goes to 100%.

Works fine in Chrome, though.

Firefox 34.0.5, OSX.

**Comment by Kerdale** [comment]
I've a similar issue with Firefox 34.0.5. <code>progress</code> events are fired after <code>success</code>.
Works fine with Chrome 39.

**Comment by danialfarid** [comment]
If you guys have steps to reproduce I can investigate more, otherwise it might have been fixed as a side effect in the newer versions.
