### ISSUE TITLE
append-to-model attribute

### ISSUE THREAD

**Issue by bolemeus** [danialfarid/angular-file-upload#445]
First of all, this is an amazing library. Kudos.

Having said that, I'm looking for an option for the ng-file-select and ng-file-drop directives to optionnaly append to the model.

I've already accomplished this by using ng-file-change and keeping the selected files in an secondary model. It works, but I don't like keeping more than necessary.

Is there something obvious I'm overlooking, or is there no way of making the directives append to the model yet?

PS: I'm showing the files in a list now, with a delete file button, so the user has full controll of what files to attach. It doesn't make sense to overwrite all files on a new drop or a new file-select event.

**Comment by danialfarid** [comment]
This could be easily handled outside the plugin you just keep adding the files to a scope variable upon file changes. I would keep the plugin code minimal

**Comment by miskin200** [comment]
Hello,
Since I'm new to angular is it possible to get an explanation how to handle this functionality?
I also want to append files to the current list, not to reset the list every time user triggers select event.

Currently I have this attributes inside my div tag:
<code>
ngf-drop ng-model="msgoriginal.attachments" ngf-multiple="true" ngf-drag-over-class="dragover"
<code>

How should my code inside controller look like so the the functionality above is achieved?

Thank you very much for the plugin!

**Comment by bolemeus** [comment]
At the moment it was not possible to do this. Im not sure if this has changed.
The way I accomplished this is by appending all new files to a new list.

you have the dropzone...

```
<div ng-file-drop ng-model="files" multiple="true" drag-over-class="{accept:'dragaccept', reject:'dragreject', delay:100}"  ng-file-change="fileSelected($files, $event)">
...
</div>
```

ng-file-change points to a function in your controller. Mine does the following:

```
$scope.fileSelected = function(files, event) {
	files.forEach(function(file) {
		if (!contains($scope.attachments, file, "name")) {
			$scope.attachments.push(file);
		}
	})
}

function contains(array, element, attribute) {
	for (var i in array) {
		if (attribute !== undefined) {
			if (array[i][attribute] == element[attribute]) {
				return true;
			}
		} else {
			if (array[i] == element) {
				return true;
			}
		}
	}
	return false;
}
```

Everytime the user adds new attachments, they are added to the scope variable attachments if they are not allready present in it. This prevents the user from adding thesame file multiple times. The contains function is just a helper function.

Finally I show the list of attachments on screen in the dropzone...
```
<ul class="list-group" ng-if="attachments.length > 0" ui-sortable="sortableOptions" ng-model="attachments" >
	<li class="list-group-item grab" ng-repeat="file in attachments" ng-attr-title="{{file.name}}">
		<i class="fa fa-file-pdf-o"></i> {{file.name}}
		<button type="button" class="btn btn-xs btn-danger pull-right" ng-click="attachments.splice($index, 1)">
			<i class="fa fa-trash"></i>
		</button>
	</li>
</ul>
```

This shows the attachments in a list with a button to remove the attachment, so the user can change the final list beofre submitting the form. Note that the classes are from bootstrap and font-awesome.

**Comment by miskin200** [comment]
Thank you @bolemeus for your reply!

I've tried your code, but a problem occurred.

On the app sample page http://jsfiddle.net/3t50b3fw/ there is a piece of code:
<code>
    $scope.$watch('files', function () {
        $scope.upload($scope.files);
    });
</code>
Do I also need to have this in my controller?
If I don't include this nothing happens. But if I include it I get an error - 
<code>
TypeError: Cannot read property 'forEach' of undefined
</code>
for the line where is files.forEach(function(file) {

Should I include "files" as a dependency for my controller or somewhere else?

Like I said I'm quite new to angular, so please excuse my question if it's to trivial.
Thank you one more time!

**Comment by bolemeus** [comment]
The snippet you provided watches the files array, and uploads the files if there is any change (I think). I don't know if that's what you want, but you can achieve thesame thing within the ng-file-change handler.

The error you're getting is related to the variable files not being initialised. To be honest I'm not sure why the function is being called with an undefined variable. When the user adds attachments the files array shouldn't be empty.
