### ISSUE TITLE
Sending JSON data along with file

### ISSUE THREAD

**Issue by bolemeus** [danialfarid/angular-file-upload#449]
I'm trying to send a file with some metadata to a Spring Controller at the backend, but I'm not having much luck. I think I narrowed the problem down to the absence of a content-type to go along with the json-data.

The request send is something along the lines of...

------WebKitFormBoundarywdhA8TIFsWhbSoX9
Content-Disposition: form-data; name="meta-data"

{"metadata":{...}}
------WebKitFormBoundarywdhA8TIFsWhbSoX9
Content-Disposition: form-data; name="file"; filename="2014-03-invoice.pdf"
Content-Type: application/pdf

In order for my Spring controller to recognize the meta-data as JSON (to map it to an object defined in my backend) the content type needs to be set to application/json, as shown in these docs... http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-multipart-forms-non-browsers

I've tried using the formDataAppender but I'm either not using it right, or it isn't possible to accomplish this with it.

My Spring controller (for completeness' sake)

```
	@RequestMapping(value = "/processwithfiles/", method = RequestMethod.POST)
	public void processWithFiles(@RequestPart("meta-data") final Document document,
			@RequestPart("file") final MultipartFile[] files, final HttpServletResponse response) {
		...
	}
```

This throws an HttpMediaTypeNotSupportedException "Content type 'application/octet-stream' not supported"

I've noticed that when I use the annotation @RequestParam instead, it works, but only if I change the type of the meta-data to String. That would require me to parse this string to a JSON object myself.

Is there a way make sure the request looks like the one in the example...
http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-multipart-forms-non-browsers

**Comment by danialfarid** [comment]
In version 3.0.0 you can set the option `sendObjectsAsJsonBlob` to send the data or field object as a json blob with concent-type `application/json` in the form data.

**Comment by bgreeley** [comment]
I'm having trouble getting this to work. I'm assuming that sendObjectsAsJsonBlob turned into sendFieldsAs. Is that correct? Is there a working example somewhere?

**Comment by danialfarid** [comment]
@bgreeley yes that's the equivalent of that option. `sendFieldsAs: json-blob`

**Comment by bgreeley** [comment]
Thanks, @danialfarid. I can't seem to get the content type to set correctly though. I'm trying to it set to application/json. Is there some example code somewhere I could see to see where I'm going wrong?

**Comment by danialfarid** [comment]
@bgreeley http://jsfiddle.net/danialfarid/tqgr7pur/ if you send the file with username you will see in the network tab that the username is being sent with `content-type` `application/json`.

**Comment by bgreeley** [comment]
Thanks, @danialfarid. I see the output. With the following config:
```javascript
fields: {
    data: {
        caption: 'caption!',
        tags: ['abc', 'def']
    }
},
sendFieldsAs: 'json-blob'
```
I'm getting the following output:

------WebKitFormBoundaryA
Content-Disposition: form-data; name="data"; filename="blob"
Content-Type: application/json
------WebKitFormBoundaryA

And if have change **sendFieldsAs** to be "json", I see the following output:

------WebKitFormBoundaryB
Content-Disposition: form-data; name="data"
{"caption":"caption!","tags":["abc","def"]}
------WebKitFormBoundaryB

Is there a reason why the content type couldn't be set to "application/json" in this case? Is this maybe a bug with the library or is this a limitation of FormData? I read through the MDN and saw that FormData could either by a File, Blob, or string. It didn't see any mention of limitations or guidelines around setting content types. Just for reference, I'll throw the link in here:

https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects

**Comment by danialfarid** [comment]
only blob can have type

**Comment by raghala** [comment]
Hi Danial,

I am using this service for to file upload, All the things going well, but when you pass korean data as input it is converting to some double byte characters. 

Could you please help me? Even you can test  in http://embed.plnkr.co/mTyI676rSKh8WnjJoDQ0/ 
In the place username please give 안녕.

**Comment by danialfarid** [comment]
@raghala  That's just the server response. if you see the network tab you will see that the data is being sent correctly
