### ISSUE TITLE
formDataAppender seems to not work as intended

### ISSUE THREAD

**Issue by Veske** [danialfarid/angular-file-upload#453]
So I am using the $upload.upload method to upload my file to Rails server.

The problem with it is that I am not able to put the file param that is sent to the server under my data.
So I attempted to try out the formDataAppender to append the file to formData.

But when I do that, the data sent is empty:

Started POST "/media.json" for 127.0.0.1 at 2014-12-14 11:14:29 +0200
Processing by Content::MediaController#create as JSON
  Parameters: {"medium"=>"{}"}
  User Load (0.3ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1  ORDER BY "users"."id" ASC LIMIT 1
Completed 500 Internal Server Error in 2ms

NoMethodError - undefined method `permit' for "{}":String:

Here is my angular code: 
$scope.upload = ($file) ->
		fileReader = new FileReader()
		fileReader.readAsArrayBuffer($file[0])
		fileReader.onload = (e) ->
			console.log(e.target.result)
			$upload.upload(
				url: "/media.json"
				data: medium: {}
				formDataAppender = (fd, key, val) ->
					if angular.isArray(val)
						angular.forEach val, (v) ->
							fd.append key, v
					else
						fd.append key, val
				file: $file[0]
				fileFormDataName: 'image_video'
			).progress((evt) ->
				console.log "percent: " + parseInt(100.0 * evt.loaded / evt.total)
			).success((data, status, headers, config) ->
				console.log data
			)

**Comment by jayrmotta** [comment]
Hey @Veske, correct me if I'm wrong but I think you haven't installed [strong parameters](https://github.com/rails/strong_parameters) as recommended in the README file, that's why you can't use the `permit` method.

**Comment by danialfarid** [comment]
Closing this cause of inactivity.

**Comment by dsmithco** [comment]
With release 3 I think you need the following...


          fields : {
            // fields to post with the file
          },
          fileFormDataName: 'asset', // name of the paperclip attachment field
          file: file
