### ISSUE TITLE
On IE8, when upload large files, flash loads the whole file into memory, and crashes 

### ISSUE THREAD

**Issue by streamone** [danialfarid/angular-file-upload#456]
I tried it on IE8, small files are uploaded successfully.
But when uploading big files, there are some problems about FileAPI.

In debug log, it stopped after print: "LOG: (flash -> js).log: ImageFactory loadFile. LOG: (flash -> js).log: ImageFactory no overlay provided".
After some minutes, it goes on and print "LOG: (flash -> js).log: ImageFactory loadFile complete, success true".

**It seems like, flash would load the whole file into memory before it upload the file to server. And it doesn't free the memory after the upload.The browser hold more and more memory spaces util the flash crashes.**
Uploading only one large file over the computer memory size would also make the crash. It took a long time to load the file, and finally crashed at "LOG: (flash -> js).log: ImageFactory create Bitmap".

So, why it loads any type of file into memory and try to create a bitmap? Is there some methods to skip over this action?

My execution environment: 
WIN7-32bit, IE8, Flash 15.0.0.223
AngularJS 1.2.26
angular-file-upload 2.0.4

The whole log is:

LOG: FileAPI: 2.0.7
LOG: protocol: http:
LOG: doctype: [undefined] undefined undefined
LOG: meta.http-equiv: IE=edge
LOG: FlashAPI.state: awaiting
LOG: (flash -> js).log: storeKey=4080614022050727353072930307296040_2.0.7
LOG: (flash -> js).log: timeout=0
LOG: FlashAPI.state: ready
LOG: FlashAPI.event.mouseenter: [object Object]
LOG: (js -> flash).multiple: true
LOG: (flash -> js).log: parseCmd, command: multiple
LOG: (js -> flash).accept: *
LOG: (flash -> js).log: parseCmd, command: accept
LOG: FlashAPI.event.select: [object Object]
LOG: FlashAPI.Form.toData
LOG: FlashAPI.XHR._send: fileapi14185455961922 -> 1418545600622541
LOG: (js -> flash).getFileInfo: [object Object]
LOG: (flash -> js).log: parseCmd, command: getFileInfo
LOG: (flash -> js).log: getFileInfo, fileID: 1418545600622541, callback: FileAPI.Flash._fn.fileapi14185455961928
LOG: (flash -> js).log: ImageFactory loadFile
LOG: (flash -> js).log: ImageFactory no overlay provided
LOG: (flash -> js).log: ImageFactory loadFile complete, success true
LOG: (flash -> js).log: ImageFactory create Bitmap

**Comment by danialfarid** [comment]
This is fixed in version 2.1.1

**Comment by streamone** [comment]
Good job!  Thanks. It does help me a lot.
