### ISSUE TITLE
how to issue an abort() on user request?‏

### ISSUE THREAD

**Issue by DarkComets** [danialfarid/angular-file-upload#457]
Hello Danial,

First of all thank you for your great efforts in ng-file-upload. Your work saves us alot of valuable time.

I went through your lib code but couldn't figure out how to abort an upload while in progress if the user wish to suddenly discontinue it.

I've seen that you return an abort() through a promise.. but that promise is only available through $upload.upload(), am I correct?

I've searched but couldn't find any references on this.

Can you tip me on this?

Thank you
Keep it up!

**Comment by danialfarid** [comment]
You can do that in your code, it depends on how you use the module, one could keep those in another global or local variable.
