### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by 7stud** [danialfarid/angular-file-upload#458]
The documentation is terrible.  If you can't document what you created, then you didn't create anything of value to anyone else.    What is the following garbled mess supposed to mean:

-------------------
<div ng-controller="MyCtrl">
  Syntax: 
&lt;button|div|input type="file"|ng-file-select|...
    ng-file-select ng-model="myFiles" // binds the selected files to the scope model
    ng-file-change="fileSelected($files, $event)" // will be called upon files being selected
                                                  // you can use $scope.$watch('myFiles') instead

---------------------------

ng-file-change does nothing for me.  The only thing that works for me is:

&lt;input type="file" ng-file-select="doSomething($files)"&gt;

Where is that documented?

Chrome Version 39.0.2171.95 (64-bit)

**Comment by clabough** [comment]
The missing piece is that the code is actually wrapped by this function in your demo, which is left out of the documentation/explanation.  It declares the 'file' variable.

	$scope.$watch('files', function(files) {
		$scope.formUpload = false;
		if (files != null) {
			for (var i = 0; i < files.length; i++) {
				$scope.errorMsg = null;
				(function(file) {
					$scope.generateThumb(file);
					eval($scope.uploadScript);
				})(files[i]);
			}
		}
		storeS3UploadConfigInLocalStore();
	});

**Comment by danialfarid** [comment]
@clabough I added that feature to the demo page to be able to dynamically modify the upload script so it would actually cal `eval` on the script string that could be edited by the user. I think this caused too much confusion as how the js is being executed. I will remove this feature in the next releases and just have all the js scripts in one file

**Comment by clabough** [comment]
Yes, I figured that was the case. I just wanted to note here where it was coming from.

**Comment by danialfarid** [comment]
I have updated the documentation and sample a lot in version 3.0.0.
Open a separate issue if you see other issues.

**Comment by shiva-p17** [comment]
I have implemented as follows 
var file = $scope.myFile;
        console.log('file is ' );
        $scope.upload = Upload.upload({
            url: 'server/upload/url',
            method: 'POST',
            fields: { 'branch[name]': $scope.branch.name,'branch[enabled]':$scope.branch.enabled},
            file: file,
            fileFormDataName: 'branch[image]'
        });

 I'm getting the file attributes from my directive. But am getting an error when I submit is as follows 

ReferenceError: Upload is not defined

Can you please help me on this

**Comment by danialfarid** [comment]
Inject Upload and ngFileUpload dependencies to your app and controller. See the jsfiddle and docs samples.
