### ISSUE TITLE
IE9 has stopped working

### ISSUE THREAD

**Issue by aszharite** [danialfarid/angular-file-upload#463]
While using the angular-file-upload in IE9 i`m getting an error "Internet Explorer has stopped working" and the browser refreshes. I get this error everytime i try to upload a file. This happens whenever I select a file from the select file dialog.

I`m using $watch over the file input and I have flash installed.

**Comment by danialfarid** [comment]
You should post your code here.
A tip would be to follow the code in the demo page and try to make your code like that as the base working sample.

**Comment by asso1985** [comment]
Even the demo has stopped working with emulating IE9 with IE11, did you check that ?
