### ISSUE TITLE
Directory/Folder drop callback doesn't fire in Chrome

### ISSUE THREAD

**Issue by kmturley** [danialfarid/angular-file-upload#466]
It's webkit, so in theory this should work. Have traced the code down to:
angular-file-upload.js
line 411
if (!processing) {

it never gets past this line of code, even thought you can log out the file list and the files are detected correctly in the list.

**Comment by danialfarid** [comment]
I fixed the processing issue in version 2.1.0. It should fire properly now

**Comment by kmturley** [comment]
Great! also I noticed that the object returned was different cross browser. I'm sure this is a browser issue but just pointing it out
