### ISSUE TITLE
Now working on IE8 (works fine with Chrome, Firefox, etc.)

### ISSUE THREAD

**Issue by dvdpearson** [danialfarid/angular-file-upload#470]
Hi !

Everything is working fine on recent browers but doesn't work on IE8. I'm not able to find anything to help me find the problem.

With my exemple, I got alert 'CC', but nothing after. So it seems something is not working with the $upload.upload function.

Here is my files

index.html

    <script>
      FileAPI = {
      //only one of jsPath or jsUrl.
      debug: true,

      jsPath: '/bower_components/ng-file-upload-shim/FileAPI.min.js',
      jsUrl: 'http://localhost:9000/bower_components/ng-file-upload-shim/FileAPI.min.js',

      //only one of staticPath or flashUrl.
      staticPath: '/bower_components/ng-file-upload-shim/FileAPI.flash.swf',
      flashUrl: 'http://localhost:9000/bower_components/ng-file-upload-shim/FileAPI.flash.swf'

      //forceLoad: true, html5: false //to debug flash in HTML5 browsers
    }
    </script>
    <script src="bower_components/ng-file-upload/angular-file-upload.js"></script>
    <script src="bower_components/ng-file-upload-shim/angular-file-upload-shim.js"></script>

My form part : 

    <form uploader="uploader" name="pictures" enctype="multipart/form-data" ng-submit="sendPicture(picture, file)" novalidate>
    <button type="file"
                        ng-file-select
                        ng-model="file"
                        ng-file-change="fileSelected($files, $event)"
                        ng-multiple="true"
                        accept="image/*,*.pdf,*.xml"
                        resetOnClick="true">Upload</button>

                <p>Bannière: <select name="company" ng-model="picture.company">  <option>IGA</option><option>Métro</option><option>Maxi</option></select></p>
                <p>Magasin: <input type="text" name="store" ng-model="picture.store" /></p>
                <p>Desc: <textarea name="description" ng-model="picture.description"></textarea></p>
                <p><input type="submit" name="submit" value="submit" /></p>
    </form>

My scripts part : 

    $scope.sendPicture = function (picture, file) {
                picture.mission = $scope.mission.id;
                picture.user = 4;
                picture.city = 'asdasd';
                alert('CC');
                $scope.upload = $upload.upload({
                    url: 'http://URL/api/displays',
                    method: 'POST',
                    data: picture,
                    file: file
                }).progress(function(evt) {
                    alert('PROGRESS');
                    //console.log('progress: ' + parseInt(100.0 * evt.loaded / evt.total) + '% file :'+ evt.config.file.name);
                }).success(function(data, status, headers, config) {
                    // file is uploaded successfully
                    alert('EEEEE');
                    $scope.displays = data;
                });
            };

**Comment by danialfarid** [comment]
What version of the plugin are you using?

**Comment by dvdpearson** [comment]
The problem in fact was the url. I was using a distant URL, and flash do not accept distant URL.
