### ISSUE TITLE
Http status 405 while uploading a file using angularjs in spring mvc web

### ISSUE THREAD

**Issue by goelprateek12** [danialfarid/angular-file-upload#471]
I am new to angular js , need yr help while sending file from angular js to spring controller . I configured it but still it is giving me same 405 Method on request.

Request Fingerprint:----

Remote Address:[::1]:8080
Request URL:http://localhost:8080/fileUploader
Request Method:POST
Status Code:405 Method Not Allowed
Request Headersview source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Content-Length:0
Cookie:JSESSIONID=2511E9766D373973C30849E2AD0B29C5
Host:localhost:8080
Origin:http://localhost:8080
Pragma:no-cache
Referer:http://localhost:8080/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Response Headersview source
Allow:GET, HEAD
Content-Language:en
Content-Length:1047
Content-Type:text/html;charset=utf-8
Date:Sat, 20 Dec 2014 23:10:09 GMT
Server:Apache-Coyote/1.1

Any suggestion would be highly appreciated

**Comment by danialfarid** [comment]
That's a server side configuration issue. Try to get it working with a simple html form submit and then change it to angular file upload.
