### ISSUE TITLE
Where's Change Log?

### ISSUE THREAD

**Issue by litera** [danialfarid/angular-file-upload#472]
Root folder should contain a **change log.md** file with changes brought with new versions. This is especially important for **breaking changes**. Are there any breaking changes going from 1.6.x to 2.x? I know that many developers regard this a mandatory requirement.

Without a change log developers are hesitant to upgrade your plugin as they don't know whether it'll break something in their existing codebase. At least it gives them guidance what to test in their apps after an upgrade.

**Comment by litera** [comment]
Although one can actually see that there, but it's an unlikely place for developers to look for changelog. And you can't emphasize more important items there like breaking changes or other specifics that may be of interest to your users.

**Comment by danialfarid** [comment]
True, but all versions have been backward compatible so far and readme example page is a good place to know the syntax and sample of each version.

**Comment by danialfarid** [comment]
I want to keep the work needed for maintaining the plugin to the minimum so I could focus on adding features and fixes in the limited time I have to put on this open source module. If you are willing to contribute and create the change logs based off the release notes you are more than welcome.
