### ISSUE TITLE
Uploading files with drag and drop or selection.

### ISSUE THREAD

**Issue by hegek87** [danialfarid/angular-file-upload#473]
I'd like to have an area where the user can drag and drop a file to upload and click the area to select a file to upload. Currently it seems like it is only possible to either drag and drop or click (i.e. ng-file-drop, ng-file-select). Is there a way to do this that I'm just unaware of?

**Comment by danialfarid** [comment]
Fixed in version 2.1.x. You can have both directives on the same element like the demo page.
