### ISSUE TITLE
Preventing a drop event on document level

### ISSUE THREAD

**Issue by toncid** [danialfarid/angular-file-upload#482]
I haven't found a way to prevent the drop event on the document level (e.g. when the drop area is missed).

Any suggestions on how to best address this issue? Thanks!

**Comment by danialfarid** [comment]
The demo page now prevents the document level drop:
```
	window.addEventListener("dragover", function(e) {
		e.preventDefault();
	}, false);
	window.addEventListener("drop", function(e) {
		e.preventDefault();
	}, false);
```

**Comment by toncid** [comment]
Thanks! Any chance of having the library doing this automatically?

**Comment by danialfarid** [comment]
It could be an option of the directive but some people might wanna have drop event on the document.

**Comment by toncid** [comment]
This should be handled carefully, not to bound multiple identical event listeners as directive appears across multiple pages or more than once on a page.

**Comment by danialfarid** [comment]
Seems like it's better to leave it off to the user's to decide what they wanna do if the drop is happening somewhere else on the page. This keep the listeners minimal and prevent attaching a listener to the whole document.
