### ISSUE TITLE
ng-file upload does not work properly 

### ISSUE THREAD

**Issue by vuhailuyen1991** [danialfarid/angular-file-upload#483]
Here is my angular app: 

window.ethnicApp = angular.module 'ethnicApp', ['templates', 'ngRoute', 'ngResource', 'ui.router',
                                                'angularFileUpload', 'ngAnimate', 'ui.grid',
                                                'authModule', 'homeModule', 'itemsModule',
                                                'addItemModule', 'showItemModule']

Here is my slim html:

.form-group
                  label Update Images
                  input ng-file-select="onFileSelect(files)" ng-model='imageFiles' accept="image/*" type="file" multiple='multiple'

My 'onFileSelect' 
$scope.onFileSelect = (files)->
      console.log 'files', files

When I select a file that function is not triggered?. I think i did set up the dependency right, didn't I?

**Comment by danialfarid** [comment]
ng-file-select should not have a value. It is just kept there for compatibility with older versions.
instead use ng-file-change and if you use ng-file-change the name of the argument should be `$files` not `files`.
Then if you are using ng-file-change you don't need to specify ng-model. Alternatively you can just have the ng-model without ng-file-change and in your controller watch for the model change:`$scope.$watch('imageFiles', function(files){...})`

**Comment by vuhailuyen1991** [comment]
@danialfarid Thanks, I will give it a try.

**Comment by vuhailuyen1991** [comment]
@danialfarid  
```javascript
input type="file" ng-required="true" name="slide"  accept="image/*" ng-file-change="imageSelect($files, $event)"
```
Still not work for me.

**Comment by vuhailuyen1991** [comment]
I found out why, I chose the wrong version. Closing.
