### ISSUE TITLE
accept attribute ignored in Firefox

### ISSUE THREAD

**Issue by bolemeus** [danialfarid/angular-file-upload#486]
The accept attribute seems to be ignored in firefox. I've tested it in Chrome and it works fine when I set it to application/pdf. I cannot select any files other than pdf files, and when I try to drop  another file over the drop zone the correct class is being applied to it.

In firefox (33.1.1) however it is possible to select files other than pdf files, and they are appended to the files[] array. When dragging a file other than a pdf files over the drop zone the incorrect class is being applied, but when I drop a file other than a pdf file it is not being added.

This behaviour is also present in the demo. I can select files other than images or pdf files in the demo...

https://angular-file-upload.appspot.com/

dragging another file over the dropzone also causes the incorrect class to be applied to the dropzone in the demo.

I'm already using a file-change listener, so I'll try to fix it there.

**Comment by bolemeus** [comment]
Ok,

I've partially fixxed this. I'm using the file-change listener to check the file type is equal to application/pdf. If it is not, then I won't add it to the array of files.

I've discovered another strange behaviour though. It seems that the listener is not always called when a file is selected. When selecting a file twice in a row. the listener is not called the second time.

**Comment by danialfarid** [comment]
Seems like a firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=826185
But selecting the same file twice works fine for me and the model will change twice as in the demo page.
Firefox 33.1.1

**Comment by bolemeus** [comment]
Too bad Firefox is the problem here. :(

When selecting thesame file multiple times though, it surely works, but it seems the listener function is only called the first time.

ng-file-change="fileSelected($files, $event)"

The function fileSelected() is only called the first time.

**Comment by danialfarid** [comment]
This should be fixed in 3.0.0
