### ISSUE TITLE
Code is uploaded if data object contains functions

### ISSUE THREAD

**Issue by deuxpi** [danialfarid/angular-file-upload#487]
If the `data` parameter of the config contains any function, the code of this function will be sent along the form data. This is different behavior than the $http module that eventually uses JSON.stringify() which strips functions and undefined objects by default.

I would have expected to see similar behavior between $upload.upload and $http, and I definitely didn't expect to see the code of a function to be sent.

Example: http://jsfiddle.net/deuxpi/xd9h8z9c/

**Comment by danialfarid** [comment]
Since version 3.0.0 the option `fields` is replacing `data` and `data` will have the default behaviour like $http and will be send as a form data field with the name `data` along with other fields and file.
