### ISSUE TITLE
progress not working in version 2.1.1

### ISSUE THREAD

**Issue by raffsangiani** [danialfarid/angular-file-upload#491]
It's seems that progress is not working in version 2.1.1 and 2.1.0. When I bower install version 2.0.5 it works fine with my code. as soon as I use 2.1.0 or higher it doesn't. Can someone confirm that they have the same issue? 
I tried logging the progress-event from the progress-callback but it seems that the callback is never called.

**Comment by danialfarid** [comment]
The demo page is using the latest version and progress is working.
Could you provide a jsfiddle or your code here.
