### ISSUE TITLE
Issue when submit file over ~2MB

### ISSUE THREAD

**Issue by dvdpearson** [danialfarid/angular-file-upload#493]
Hi !

I am using this plugin since few weeks and I have an issue concerning uploading files with more than ~2MB.

When I select file and then click on submit, the file is detected, but when I $upload.upload() it, nothing is sent on the HTTP post. Is something wrong I am doing ?

Thanks !

**Comment by YarinSl** [comment]
Hi dvdpearson,
did you find a solution?
I'm having this problem too

**Comment by YarinSl** [comment]
Fixed it-
the problem was in my php.ini file- 
the 'upload_max_filesize' var was set to 2MB...

**Comment by dvdpearson** [comment]
Yep ! It was the PHP setting. Thank you !
