### ISSUE TITLE
Drop not updating model / watcher

### ISSUE THREAD

**Issue by dbounds** [danialfarid/angular-file-upload#503]
Since updating from an earlier version I am unable to drag/drop working. No matter what I attempt (and I've tried many variants) the $scope.myFiles model is never updated and files are never uploaded with drag/drop. If the user clicks and users the file selector everything works fine.

This was working fine in previous versions. 

I have the following markup:

```

         <div class="section">
            <div ng-file-drop="ng-file-drop" ng-file-change="onFileSelect($files), ng-model="files" drag-over-class="{accept:'dragover', reject:'dragover-err', delay:100}" class="dropbox">
               <h3>Drag A Resume Here</h3>
            </div>
            <div type="file" ng-file-select="ng-file-select" ng-model="files" ng-file-change="onFileSelect($files)" ng-if="!candidate.resume.file_name" class="upload"><i class="fa fa-plus"></i><span> or click here to upload</span></div>
         </div>
```

And supporting JS:

```
    $scope.$watch('files', function() {
        console.log('FIRED: ' + $scope.files.length);
        $scope.onFileSelect($scope.files);
    });

    $scope.onFileSelect = function($files) {
        for (var i = 0; i < $files.length; i++) {
            var file = $files[i];
            $scope.upload = $upload.upload({
                url: '/uploadURL',
                method: 'POST',
                file: file
            }).progress(function (e) {
                console.log('Percent: ' + parseInt(100.0 * e.loaded / e.total));
                $scope.fileUploadingPercent = parseInt(100.0 * e.loaded / e.total);
            }).success(function (data, status, headers, config) {
                if(data && data.url) {
                    $scope.candidate.resume = {
                        'file_name': file.name,
                        'url': data.url
                    }
                }
            });
        }
    };
```

**Comment by danialfarid** [comment]
replace `ng-file-drop="ng-file-drop"` with `ng-file-drop`

**Comment by egervari** [comment]
I also had this problem, but it was a different cause. My issue was that I was using the `translate` directive, part of angular-translate, which apparently is a big no-no when using this library.

**Comment by danialfarid** [comment]
@egervari what was the problem with angular-translate any specific error?

**Comment by egervari** [comment]
For the drop box, i used to use the `translate` directive on the div that also had the `ng-file-drop`. The solution was to use the {{}} notation for the element's actual content:

        <div ng-file-drop=""
             ng-file-select=""
             ng-model="files"
             class="dropZone"
             drag-over-class="{accept:'dragOverSuccess', reject:'dragOverError', delay:100}"
             accept="image/*">
            {{'COURSE.CHANGE_IMAGE.DROP_IMAGE' | translate}}
        </div>

This is the workaround, but if you want to play nice with the `translate` directive, then one or both of the libraries will need some code changes.

**Comment by wuv1982** [comment]
i have a similar problem :  `$watch` not work (env: angular, angular-material).
i noticed something weird about the `scope` when directive the `ng-file-select`. 
the ngModel `files` is defined in the controller's scope, but updated in its child scope when file changed.
