### ISSUE TITLE
ng-capture ?

### ISSUE THREAD

**Issue by anthonyhoman** [danialfarid/angular-file-upload#506]
This line is in the documentation:

ng-capture="'camera'|'other'" // default not included, allows mobile devices to capture using camera

I don't see this handled anywhere in the actual source code.  Am I just missing it, or is it a planned feature that's not ready yet?  Or is there some 3rd party library that I'm supposed to install?

**Comment by brohde** [comment]
I am looking for this feature too, and can't find it's implementation in the source code.

**Comment by anthonyhoman** [comment]
OK, now I feel stupid.  Didn't realize that the iPad capture functionality comes out of the box with input type="file".

**Comment by rpallas** [comment]
note that if you use `ngf-multiple`, the option to use camera for capture will not be available
