### ISSUE TITLE
Cookies is not defined

### ISSUE THREAD

**Issue by longieirl** [danialfarid/angular-file-upload#507]
We have a CI build that worked 12hours ago against angular JS v1.3.8 - angular in the last 12 hours have bumped to v1.3.9 and now our build gets the an unreferenced error, as shown:

```
Uncaught ReferenceError: cookies is not definedangular-file-upload-shim.js:4 19../angular-cookies_prelude.js:1 s_prelude.js:1 (anonymous function)app.js:35 292../requires.js_prelude.js:1 s_prelude.js:1 e_prelude.js:1 (anonymous function)
```

Just wondering if anybody else has seen this issue? Reverting back to version 1.3.8 works.

J

**Comment by longieirl** [comment]
Just wondering if anybody else is having issues with this? The latest update to angular does not work as expected with file-upload.

**Comment by danialfarid** [comment]
angular-file-upload is not usiing cookies. It is probably from your other dependencies.

**Comment by danialfarid** [comment]
The demo page works with 1.3.9.
Could you narrow down which library is conflicting with this plugin? It might be angular-cookies that is conflicting.

**Comment by longieirl** [comment]
The latest version bump 1.3.13 of Angular seems to have resolved this issue.
