### ISSUE TITLE
upload doesn't work on iPhone 6

### ISSUE THREAD

**Issue by pbilyk** [danialfarid/angular-file-upload#512]
I am using version 2.0.4.  When I try to upload a file from iPhone 6, I get error with code 4.

Version 2.1.0+ doesn't work for me, probably because I'm invoking this in a modal window (there's an issue for that: https://github.com/danialfarid/angular-file-upload/issues/511).

**Comment by danialfarid** [comment]
Can you create a jsfiddle? You can use this as base:
http://jsfiddle.net/deuxpi/xd9h8z9c/

**Comment by qdb** [comment]
Please check your [demo website](https://angular-file-upload.appspot.com/). The upload does not work on my iphone 5s. It shows file size and type after I select a photo from my library, but stops upload at 0%.

**Comment by qdb** [comment]
Based on [this post](http://blog.uploadcare.com/you-cannot-upload-files-to-a-server-using-mobile-safari/) I realized this can be an iOS issue. I have updated my device and it works as expected now. Sorry for bothering and many thanks for this library.

**Comment by designbyadrian** [comment]
@qdb Which version of iOS? You can't rely on all users to have the same OS version as you, so we need to look into this issue further :-|

**Comment by mtpultz** [comment]
I'm using Browserstack to debug an issue uploading on iOS right now it doesn't work of iPhone 7, iPhone 6 and 6S, but does appear to allow uploads of images in iPhone5.  

When the button is clicked the file selection dialog does not popup for iPhone 6, 6S, or 7, but does  work in all other browsers and devices, which includes Safari for Mac ver. 8, 9, and 10.  

Browserstack has dev tools for iPhone 6 and 6S, and both display no errors.  I just appears as if the button doesn't work.

```
<button type="button"
        ng-if="section.action.type === 'file-upload'"
        class="button-primary-full-width"
        ngf-select="vm.upload($files, $invalidFiles, section.action.action_id)"
        ngf-select-disabled="vm.selectDisabled"
        ngf-multiple="vm.multipleUploads"
        ngf-max-files="vm.maxFiles"
        ngf-max-size="section.action.max_size"
        ngf-accept="section.action.mime_types"
        ngf-pattern="section.action.extensions">
    {{ section.action.label }}
</button>
```

**Comment by mtpultz** [comment]
@qdb that link you provided is dead.  Can you update it?

**Comment by mtpultz** [comment]
@danialfarid using your example in Browserstack I can see that it seems to work, or at least the popup appears to upload an image.  Is there a difference in how this works comparing these two snippets?  I want to use the button not the file upload input based on our UI requirements, but the top example doesn't display the popup, while the bottom snippet does.  As I mentioned it does work everywhere else on Android, Windows, and Mac, and only iOS has issues in v6+.

```
<button type="button"
        ng-if="section.action.type === 'file-upload'"
        class="button-primary-full-width"
        ngf-select="vm.upload($files, $invalidFiles, section.action.action_id)"
        ngf-select-disabled="vm.selectDisabled"
        ngf-multiple="vm.multipleUploads"
        ngf-max-files="vm.maxFiles"
        ngf-max-size="section.action.max_size"
        ngf-accept="section.action.mime_types"
        ngf-pattern="section.action.extensions">
    {{ section.action.label }}
</button>
```

Versus

```
<input type="file"
       name="file"
       ng-file-select
       ng-model="vm.picture">
```

The markup and the request made are directly from your docs:

```
<div class="button" ngf-select="upload($file)">Upload on file select</div>
```

```
 vm.upload = function (file) {
 
       Upload.upload({
            url: 'upload/url',
            data: {file: file, 'username': $scope.username}
        }).then(function (resp) {
            console.log('Success ' + resp.config.data.file.name + 'uploaded. Response: ' + resp.data);
        }, function (resp) {
            console.log('Error status: ' + resp.status);
        }, function (evt) {
            var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
            console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
        });
    };
```

**Comment by mtpultz** [comment]
So just an update using all these examples only the one with ng-file-select works, but none of the others.  That said I can get your [example](http://jsfiddle.net/danialfarid/2vq88rfs/136/) to work, which is similar to the second example, but it doesn't show in iPhone6+.  So it seems to be related to `ngf-select` in some way.

```
// Works
<input type="file" name="file" ng-file-select ng-model="vm.picture"><br/>

// Doesn't work, but similar to working example
<button class="button" ngf-select="vm.upload($files, $invalidFiles, section.action.action_id)">Select</button>

// Doesn't work
<div class="button" ngf-select="vm.upload($files, $invalidFiles, section.action.action_id)">Select</div>

// Doesn't work
<button type="button"
        ng-if="section.action.type === 'file-upload'"
        class="button-primary-full-width"
        ngf-select="vm.upload($files, $invalidFiles, section.action.action_id)"
        ngf-select-disabled="vm.selectDisabled"
        ngf-multiple="vm.multipleUploads"
        ngf-max-files="vm.maxFiles"
        ngf-max-size="section.action.max_size"
        ngf-accept="section.action.mime_types"
        ngf-pattern="section.action.extensions">
    {{ section.action.label }}
</button>
```

**Comment by mtpultz** [comment]
I've also stubbed through all the the methods invoked when clicking one of the `ngf-select` elements in the examples above.  The sequence followed for iOS and others is the same, but at the end the popup just doesn't appear for iOS like the others.  It ony displays for the input with the `ng-file-select` directive.

**Comment by mtpultz** [comment]
I couldn't figure it out so I went for an older solution that still works.

```
<label class="button-primary-full-width button-upload">
    <span>Choose File</span>
    <input type="file"
           class="file-upload"
           ngf-select="vm.upload($files, $invalidFiles, section.action.action_id)"
           ngf-select-disabled="vm.selectDisabled"
           ngf-multiple="vm.multipleUploads"
           ngf-max-files="vm.maxFiles"
           ngf-max-size="section.action.max_size"
           ngf-accept="section.action.mime_types"
           ngf-pattern="section.action.extensions">
</label>
```
