### ISSUE TITLE
Charset encoding on filenames

### ISSUE THREAD

**Issue by mateusleon** [danialfarid/angular-file-upload#513]
Hello Dani,

I'm facing one problem that is the encoding of the filename. Currently, I'm trying to do this upload from a "ltr" application, sending one file with "rtl" name.

The problem is that the filename is sended on the POST, visually correct, but the server isn't receiving it clearly, and without the "utf-8" information to deal with.

See the print below:

![upload-print](https://cloud.githubusercontent.com/assets/5111126/5803337/b1153120-9fe4-11e4-9249-921c16e67bd9.png)

The problem is that, when the server receive the data, the filename isn't recognized corretly, due to lack of information on the request. I need the ability to inform the charset, even if I'm dealing with old browsers (non-HTML5), while the `header: { ... }` param on the plugin is only for HTML5 browsers.

Can you give some help about this issue? Thank you.

**Comment by danialfarid** [comment]
I think it is your server side that doesn't use the correct encoding. The request being sent seems fine and the filename is shown correctly.

**Comment by mateusleon** [comment]
No, the server is handling the requests correctly, because the same service is receiving through other apps their file uploads and the filenames are being shown correctly.

The module on the server side doesn't appear to be causing this issue. I've dealt with this problem palliatively using `encodeURIComponent(filename)`, rewriting it on the `upload()` options:

```
                $scope.upload[index] = $upload.upload({
                    url: 'path-to-api',
                    method: 'POST',
                    file: file,
                    fileName: encodeURIComponent(file.name)
                });
```

But it has to be resolved in a better way. This not seems correct.

**Comment by danialfarid** [comment]
If you try the demo page you can see that it could upload utf-8 filenames and the response comes back with the correct name, you just need to set the charset of your request/response on your server side properly to utf-8.
