### ISSUE TITLE
Demo missing a large amount of context

### ISSUE THREAD

**Issue by jacobscarter** [danialfarid/angular-file-upload#515]
Some examples:

In the edit upload script:

    file.upload = $upload.upload({

Where is file declared as an object, where is upload created as a property on that object

    url: 'https://angular-file-upload-cors-srv.appspot.com/upload' + $scope.getReqParams(),

Where is $scope.getReqParams() defined

**Comment by asael2** [comment]
Yes please, hours trying to figure it out with the examples, even dealing with typo errors,.. cmon guys!!

**Comment by danialfarid** [comment]
fixed in version 3.0.0
