### ISSUE TITLE
Add window.console existence checks

### ISSUE THREAD

**Issue by toncid** [danialfarid/angular-file-upload#521]
Hello,

Great library! :) 

I suggest you add some simple `console` existence checks to prevent null exceptions in IE.

For example (in https://github.com/danialfarid/angular-file-upload/blob/master/dist/angular-file-upload.js#L474):

```javascript
    ...
  } catch (e) {
    processing--;
    if (window.console) {
      console.error(e);
    }
  }
  ...
```

Thoughts?

**Comment by danialfarid** [comment]
This code is only executed for webkit chrome which supports directory upload, so console.error exists.

**Comment by toncid** [comment]
Makes sense. :)
