### ISSUE TITLE
Create Drag Validation Hook

### ISSUE THREAD

**Issue by lancecaraccioli** [danialfarid/angular-file-upload#524]
Feature request to create an attribute that validates if the current drag operation should be handled by ng-file-upload at all.  I currently have a conflict with another drag/drop directive for non-file items.  Logically I only want to handle File type items with ng-file-upload.  Other items should fall through to other handlers and ng-file-upload should ignore that drag.

**Comment by danialfarid** [comment]
You can use `drag-over-class=calculateDragOverClass($event)` to change the drag over class on the file element.
The drag event is just handled to calculate the visual class of the element and if you drop it and there is no file in it it would be ignored.

**Comment by danialfarid** [comment]
You can use this method as a reference/sample:
https://github.com/danialfarid/angular-file-upload/blob/master/dist/angular-file-upload.js#L374

**Comment by danialfarid** [comment]
https://github.com/danialfarid/angular-file-upload/blob/master/dist/angular-file-upload.js#L374
