### ISSUE TITLE
Update NPM version

### ISSUE THREAD

**Issue by steelsojka** [danialfarid/angular-file-upload#530]
The current version in NPM is 1.6.4. Can this be updated to the latest release. Would be nice to be able to use with browserify. Thanks.

**Comment by danialfarid** [comment]
I have published in under the name `ng-file-upload`. I will publish new versions on npm as part of the build.

**Comment by danialfarid** [comment]
It is added to readme file

**Comment by steelsojka** [comment]
Thank you for this!
