### ISSUE TITLE
Package not updated for 3.0.0 release

### ISSUE THREAD

**Issue by Oceanswave** [danialfarid/angular-file-upload#536]
Doesn't look like the changes made it in

https://github.com/danialfarid/angular-file-upload/archive/3.0.0.zip <-- contains files marked 2.2.2

https://github.com/danialfarid/angular-file-upload/blob/master/dist/ng-file-upload-all.js <-- empty file..
 

Sorry!

**Comment by digioak** [comment]
@Oceanswave Funny running into you here -- I'm using this Angular control too!

**Comment by danialfarid** [comment]
It's fixed at version 3.0.1.
Thanks for reporting.

**Comment by Oceanswave** [comment]
Thanks!

And hey @digioak !!
