### ISSUE TITLE
Chrome is crashing while trying to select a file

### ISSUE THREAD

**Issue by patrickse** [danialfarid/angular-file-upload#539]
Hi,

I´ve googled for a while now, but I can´t find any solution for my problem. I just try to upload rather small files... <1 MB and I am using angular-file-upload. As soon as I hit the "Select files"-Button in Chrome, it opens the file dialog and then crashs. That does not happen everytime, but at least to often.

I can reproduce the crashs if I go and click quite fast on this button right after the page has been loaded.

Does anyone else experience this problem? I´ve tried Firefox and it´s just working. It looks like it´s just Chrome.

Hope you can help,

Patrick

**Comment by rigobcastro** [comment]
RAM?

**Comment by patrickse** [comment]
Hmm,

I don´t think so. Actually my laptop has about 8GBs of RAM and the upload file is 300kb. That should fit into my memory.

Any other ideas?

**Comment by rigobcastro** [comment]
Ok, Do you have any extension? I have problems with Dropbox extension, it crash my chrome. Try again in private navigation.

**Comment by patrickse** [comment]
Hmm.. I´ve tried private navigation... looks like my problem.

**Comment by danialfarid** [comment]
If you figure out which extension causes that problem please post it here for other people to know.
