### ISSUE TITLE
Get server side file name

### ISSUE THREAD

**Issue by adavia** [danialfarid/angular-file-upload#540]
Im wondering how to get the server's side filename on the success callback in order to push the result into an array. The problem is that i only can use "file" which is the selected file and not the renamed file i should get from the server.

if (files && files.length) {
                for (var i = 0; i < files.length; i++) {
                    var file = files[i];
                    $upload.upload({
                        url: '/api/users/profile/' + username,
                        fields: data,
                        file: file
                    }).progress(function (evt) {
                        var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                        console.log('progress: ' + progressPercentage + '% ' +
                                    evt.config.file.name);
                    }).success(function (data, status, headers, config) {
                        console.log(data.files);
                        console.log('file ' + config.file.name + ' uploaded. Response: ' +
                                    JSON.stringify(data));
                        if(files.length > 0){
                            for (f in files){
                                $scope.user.profile.pictures.push(files[f]);
                            }
                        }else{
                            $scope.user.profile.pictures.push(file); //Need to use server's file name
                        }
}

**Comment by danialfarid** [comment]
If it's just the name, send the name back in your response and get it from `data` in the response
```
.success(function (data, status, headers, config) {
    console.log(data.fileNames);
}
```

If you need to show the file that is on the server then you need to download it first to the browser and then show it.

**Comment by adavia** [comment]
So i guess the best idea is to reload the div instead of pushing the file into the array in case i need to show the file from the server
