### ISSUE TITLE
Drop box isn't working.

### ISSUE THREAD

**Issue by AdamJessop** [danialfarid/angular-file-upload#543]
Not sure if I am doing anything wrong, but I am getting the same results from your demo.
When dragging files over to the drop box, it is triggering the $watch on my model however it is not getting fired. I noticed that on your demo: https://angular-file-upload.appspot.com/ and your JSFiddle: http://jsfiddle.net/wsoLzeur/ have the same issue. Clicking to select the file works fine, however dragging over and uploading doesn't give the desired result.

Here is my current directive:

```html
 <div ng-file-select ng-file-drop ng-model="file" class="drop-box"
                     drag-over-class="{accept:'dragover', reject:'dragover-err', delay:100}" ng-multiple="false" allow-dir="true"
                     ng-accept="'*.mp3,*.wav,*.ogg,*.flac'">

                       Drop files here or click to upload
                </div>
````

Hope you can help.

**Comment by danialfarid** [comment]
What browser/version? What do you mean by doesn't give the desired result?

**Comment by AdamJessop** [comment]
Using Chrome and Firefox latest and greatest (I checked for updates).

Quite simply when I drag a file into the drop box area, my files variables both the $scope model bound and the $files arguement passed to the ng-file-change function is an empty array. Or it sometimes strangely gets set to an empty object. 

No file information can be seen.

When using the ng-file-change function I am simply console.log'ing the $file arguement:

````javascript
 $scope.fileDropped = function($files) {
        console.log($files);
        $scope.file = $files[0];
        console.log($scope.file);
    }
````

And as you can see here, I am simply not getting a file object:

![image](https://cloud.githubusercontent.com/assets/6536024/6071016/90753958-ad89-11e4-80ed-918e108c09eb.png)

**Comment by danialfarid** [comment]
The files are probably rejected. try this:
```
 $scope.fileDropped = function($files, $rejectedFiles) {
        console.log($files, $rejectedFiles);
        $scope.file = $files[0];
        console.log($scope.file);
    }
```

**Comment by AdamJessop** [comment]
Nope, I did try that earlier and as I said, the click to upload feature works fine. 

````javascript
$scope.fileDropped = function($files, $event, $rejectedFiles) {
        console.log($files, $rejectedFiles);
        console.log($event);
        $scope.file = $files[0];
        console.log($scope.file);
    }
````

![image](https://cloud.githubusercontent.com/assets/6536024/6071179/f9bacf9e-ad8a-11e4-91ce-a17a0e48bd9d.png)

Again, this behaviour is also reproducible on your own demos

**Comment by AdamJessop** [comment]
Also within that mouse event, the dateTransfer.files object is also empty, not sure if that is applicable or not.

**Comment by AdamJessop** [comment]
Ah, you know what, I see the issue.

I didn't realise I was dragging the file object from a .zip, thanks windows .zip folder support!
I guess some kind of error catching needs to be employed.
