### ISSUE TITLE
fileName/fileType not sent in payload

### ISSUE THREAD

**Issue by arabesq610** [danialfarid/angular-file-upload#544]
When I send explicit fileName and fileType with my upload config object, they're not being sent with the payload. Is it possible to include the fileName and fileType with the payload?

Content-Disposition needs to include the filename, and Content-Type needs to be included for each file in the request payload.

For example, I would like this payload:
```
Request Payload
------WebKitFormBoundaryr7ZN2pgzDbkOfAwn
Content-Disposition: form-data; name="file1"; filename="file1.jpg"
Content-Type: image/jpeg
```
...as opposed to what's currently being sent:
```
Request Payload
------WebKitFormBoundaryAL6WjUHQQOSjGbMy
Content-Disposition: form-data; name="file1"
```

This would be an example of the config including filetype:
```
$upload.upload({
  url: url,
  headers: headers,
  fileFormDataName: ['file1', 'file2'],
  fileName: [$scope.formData.file1[0].name, $scope.formData.file2[0].name],
  fileType: [$scope.formData.file1[0].type, $scope.formData.file2[0].type],
  file: [$scope.formData.file1, $scope.formData.file2]
})
```

Is this already possible, and am I just missing the proper way to do it, or is this not currently supported?

**Comment by danialfarid** [comment]
You can change the  name and filename but not the content type.

**Comment by danialfarid** [comment]
http://jsfiddle.net/jm9bwtdq/

**Comment by danialfarid** [comment]
The content-type is part of the file object so it is not calculated or set by the plugin.

**Comment by arabesq610** [comment]
Thanks!
