### ISSUE TITLE
data is not being sent to the apiController

### ISSUE THREAD

**Issue by texas697** [danialfarid/angular-file-upload#545]
I have been stuck on this all day. I have now copied and pasted into my project but i still end up at the same place. the image is making it to the angular controller, but once it passes var file = files[!] it loses it. so i am getting a null error in the api. any help would be great.

 $scope.$watch('files', function () {
        $scope.upload($scope.files);
    });

    $scope.upload = function (files) {
        if (files && files.length) {
            for (var i = 0; i < files.length; i++) {
                var file = files[i];
                $upload.upload({
                    url: 'api/apiFiles/File',
                    fields: { 'companyName': $scope.companyName },
                    file: file
                }).progress(function (evt) {
                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                    console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
                }).success(function (data, status, headers, config) {
                    console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
                });
            }
        }
    };

**Comment by danialfarid** [comment]
create a jsfiddle

**Comment by texas697** [comment]
got a plunker
http://plnkr.co/edit/lGjgTIeVZdgxcS2kaE7p?p=preview

**Comment by danialfarid** [comment]
This works for me, what browser are you using? So you are saying that the request is not being sent to the server? Can you see the network tab in the debugger and post the request being sent here.

**Comment by texas697** [comment]
Just figured out its not the JavaScript. My apicontroller is having issues.
Sorry to bother you!
