### ISSUE TITLE
Completion redirects to upload URL

### ISSUE THREAD

**Issue by amcclung** [danialfarid/angular-file-upload#546]
I'm trying to send a file in a restful environment. When the file finishes uploading and I get a response from the server, I'm redirected to the upload url. My code is as follows:

  $upload.upload({
                url: "/api/mport",
                fields: {type:$scope.import_form.type},
                file: $scope.import_form.file
            }).progress(function(event) {...})
            .success(function(data, status, headers, config) {...});

When complete, I'm taken to http://localhost:8000/api/import in my browser.

**Comment by danialfarid** [comment]
What do you do in your success function code?

**Comment by amcclung** [comment]
Just a bunch of console.log statements for the different parameters.

**Comment by danialfarid** [comment]
Post your html here, you probably have a form submit with action and that form submit takes the user to that url. You don't need a submit action for this upload.

**Comment by amcclung** [comment]
I don't have a submit action, but here's my HTML:

<form ng-show="'Create'==mode" class="form form-inline">
  <div class="row top-buffer">
    <div class="col-md-12 centered"><h1>Import Recipe</h1></div>
  </div>
  <div class="row top-buffer">
    <div class="col-md-12 centered">
      <div class="input-group left">
        <label>Type</label>
        <select class="form-control" ng-model="import_form.type" ng-disabled="loading">
          <option value="bsmx" selected>bsmx</option>
        </select>
      </div>
      <div class="input-group left">
        <label>File</label>
        <input type="file" class="form-control" ng-file-select ng-model="import_form.file">
      </div>
      <div class="input-group left">
        <label>&nbsp;</label>
        <button type="button" class="form-control btn btn-lg btn-neutral" ng-click="import();" ng-disabled="loading">Go</button>
        <span class="loading-icon loading-icon-dark" ng-show="loading"> </span>
      </div>
    </div>
  </div>
</form>

**Comment by danialfarid** [comment]
If you create a jsfiddle off the reame example I can investigate more.

**Comment by amcclung** [comment]
So, I'm not entirely sure what I was doing wrong but, between now and when I opened this issue, the redirect stopped happening. The only thing I can think of is that I might have had some debug code active somewhere that was doing it. But I honestly can't say for sure if that was it because I haven't been able to make it happen again. At any rate, thank you for looking into this. If it does happen again I'll make sure to put it in a jsfiddle or something first to make sure it's not something on my end.
