### ISSUE TITLE
Multiple files, single request discards filename and filetype

### ISSUE THREAD

**Issue by arabesq610** [danialfarid/angular-file-upload#549]
I am working with an API that requires multiple files be sent with a single request, each with their own name property. However, the payload discards some of the file info, including the content type and filename, when the request occurs.

See http://jsfiddle.net/arabesq610/7220n1rg/

Is it possible to send multiple files in one request while preserving filename and content-type with the payload?

This relates somewhat to both #542 and #544.

**Comment by danialfarid** [comment]
The request looks fine to me it has the correct form-data names.

**Comment by arabesq610** [comment]
It does include the correct form data names, but if you look at the payload, only the name is sent. Whereas in your demo and fiddle, the payload includes Content Type for each file, as well as the filename. If you diff the payload in my fiddle: http://jsfiddle.net/arabesq610/7220n1rg/ vs http://jsfiddle.net/jm9bwtdq/ , I think you'll see what I mean.

**Comment by danialfarid** [comment]
I fixed your example: http://jsfiddle.net/danialfarid/7220n1rg/4/
you need to get the first file element and put it in the files arrays. the file model is an array even if you select one file.
