### ISSUE TITLE
Zip file discarded when using "application/zip" for ng-accept and select zip file.

### ISSUE THREAD

**Issue by parallelbgls** [danialfarid/angular-file-upload#553]
input class="form-control" type="file" ng-file-select ng-model="keywordFile" name="file" ng-accept="'application/zip'" required /
Writing in html, then select a zip file, but the zip file would be discarded and no file selected. This happens in version 3 but not happens in version 2.

**Comment by danialfarid** [comment]
It works in the demo page if you edit html and change the ng-accept to application/zip.
What browser are you using? Can you create a jsfiddle?

**Comment by parallelbgls** [comment]
I'm using the demo and it rejected either. Capture photos are here.
![default](https://cloud.githubusercontent.com/assets/4566128/6139943/b30ca680-b1cc-11e4-8c1d-ba88d9fb103c.PNG)
![2](https://cloud.githubusercontent.com/assets/4566128/6139944/b66f2960-b1cc-11e4-8d59-3e616888d68c.PNG)
Operating System is Windows 8.1 and browser is chrome 40.0.2214.93 (64-bit)

**Comment by parallelbgls** [comment]
Update to 40.0.2214.111 m (64-bit), it happens either.

**Comment by danialfarid** [comment]
Maybe the file you are choosing is not of mime type 'application/zip'. Check the files type or try ng-accept="'.zip'"

**Comment by parallelbgls** [comment]
When I using '.zip', it also rejected my file. 
![default](https://cloud.githubusercontent.com/assets/4566128/6206134/78db6b54-b5be-11e4-8a0d-d0961520b5e6.PNG)
![2](https://cloud.githubusercontent.com/assets/4566128/6206135/7b25a85c-b5be-11e4-9c51-eb0f6898602b.PNG)
I have to repeat that type selected is correct but updated this file will return rejected, and this function is correct is verstion 2.x, but not function properly in version 3.x

**Comment by parallelbgls** [comment]
By the way, 'application/zip' is really an MIME type.
![3](https://cloud.githubusercontent.com/assets/4566128/6206215/eb4bbba2-b5bf-11e4-8552-cb5194446e61.PNG)

**Comment by danialfarid** [comment]
That's version 3 feature to validate the file's type or extension against the provided ng-accept.
The file you select is probably don't have proper type or name, you can debug the code and see the properties of the file object being passed to `ng-model-rejected="rejectedFile"' to figure out why it is not accepted.

**Comment by danialfarid** [comment]
It should be fixed in version 3.0.5

**Comment by adamjhickey** [comment]
I ran into an issue where application/zip was fine on mac. I needed application/x-zip-compressed on Windows.
