### ISSUE TITLE
small doc fix

### ISSUE THREAD

**Issue by nathandunn** [danialfarid/angular-file-upload#554]
in your S3 example you have:

$upload.upload({
        url: $'https://angular-file-upload.s3.amazonaws.com/', //S3 upload url including bucket name
        method: 'POST',
        data : {
          key: file.name, // the key to store the file on S3, could be file name or customized
 // . . . 
        },
        file: file,
      });

It should be "fields" instead of "data".  I think all of examples are correct.  A great library.  Thanks!

**Comment by danialfarid** [comment]
Fixed, thanks
