### ISSUE TITLE
Demo link is dead

### ISSUE THREAD

**Issue by wgorder** [danialfarid/angular-file-upload#560]
I just stumbled on this component, but the demo link is dead.  A working demo goes a long way when evaluating different options.  Any chance you can get this working again?

**Comment by danialfarid** [comment]
What demo link are you talking about?

**Comment by wgorder** [comment]
https://angular-file-upload.appspot.com/ is not working for me.

Your asking made me wonder if it was a proxy issue, and it turns out it is.  Usually this dumb proxy tells you its blocking you, but for whatever reason with appspot it apparently just gives you a blank white page.  Sorry for the false report.  I guess I'll have a look at it when I get home :)
