### ISSUE TITLE
Compatibility with pace.js

### ISSUE THREAD

**Issue by azue** [danialfarid/angular-file-upload#561]
the upload won't work, when the pace.js 0.7.1 script file from the pace-Project ( https://github.com/HubSpot/pace/releases ) is included. Because Chrome reports a message with code related to this project i open a new issue here.

To reproduce the error, include the script  ```  <script src="/pace/pace.js"></script> ``` from http://github.hubspot.com/pace/ into the project sample page. 

IE11 logs just a "syntax error".
Chrome shows the following error: 
```
 Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'function (xhr) {
				if (!xhr) return;
				config.__XHR = xhr;
				config.xhrFn && config.xhrFn(xhr);
				xhr.upload.addEventListener('progress', function(e) {
					e.config = config;
					deferred.notify ? deferred.notify(e) : promise.progress_fn && $timeout(function(){promise.progress_fn(e)});
				}, false);
				//fix for firefox not firing upload progress end, also IE8-9
				xhr.upload.addEventListener('load', function(e) {
					if (e.lengthComputable) {
						e.config = config;
						deferred.notify ? deferred.notify(e) : promise.progress_fn && $timeout(function(){promise.progress_fn(e)});
					}
				}, false);
			}' is not a valid HTTP header field value.
    at Error (native)
```
I tried to fix it by myself but i have no clue of the internal use of XMLHttpRequest in angular or pace and how to get them to work together.   Any idea?

**Comment by danialfarid** [comment]
In what order do you load the libraries?
Can you create a jsfiddle off the readme sample.

**Comment by azue** [comment]
Thanks for the hint. That is strange... (javascript as its best) 
placing the pace script at the end, everything is working. 

wont work: 
``` 
    <script src="Scripts/jquery-2.1.3.min.js"></script>
    <script src="Scripts/bootstrap.min.js"></script>


    <script src="Scripts/pace.js"></script>

    <script src="Scripts/angular.js"></script>
    <script src="Scripts/angular-file-upload-shim.js"></script>
    <script src="Scripts/angular-file-upload.js"></script>
    <script src="Scripts/angular-ui-router.min.js"></script>
    <script src="Scripts/angular-ui/ui-bootstrap-tpls.js"></script>
``` 

and following order is working for me
``` 
    <script src="Scripts/jquery-2.1.3.min.js"></script>
    <script src="Scripts/bootstrap.min.js"></script>

    <script src="Scripts/angular.js"></script>
    <script src="Scripts/angular-file-upload-shim.js"></script>
    <script src="Scripts/angular-file-upload.js"></script>
    <script src="Scripts/angular-ui-router.min.js"></script>
    <script src="Scripts/angular-ui/ui-bootstrap-tpls.js"></script>

   <script src="Scripts/pace.js"></script>
``` 

I tried to make a jsfiddle but cant reproduce the error there. It looks like the order doesn't matter at jsfiddle. 

I can provide a small sample zip file if required/ interested ... since the issue is on IE/Chrome/Firefox. Anyway switching the position solved it for me.

**Comment by regnerus** [comment]
Thanks I've spent a long time figuring this one out! 

But switching the order of loading Javascript files probably isn't  the preferred fix right?

**Comment by usmanasif** [comment]
Thanks, my issue has also been resolved by changing the order
