### ISSUE TITLE
when use flash to upload cant get files. 

### ISSUE THREAD

**Issue by Johnzero** [danialfarid/angular-file-upload#563]
$scope.$watch('files', function () {
	        console.log($scope.files);
	    });
OR 
$scope.upload = function (files,event) {} 

files is empty

**Comment by vcharnahrebel** [comment]
I can reproduce that too. Based on debug log, FileAPI processes files as expected, but 'files' angular model is empty. If that's an expected behavior, is there any example of api for that flash upload?

**Comment by bigthinkit** [comment]
Same problem for me... The ngModel is empty.
I tried to test it also in Chrome with forceLoad: true.

This is the log:

FileAPI: 2.0.7
FileAPI.min.js:2 protocol: http:
FileAPI.min.js:2 doctype: [html]  
FileAPI.min.js:2 meta.http-equiv: IE=edge,chrome=1
FileAPI.min.js:2 FlashAPI.state: awaiting
FileAPI.min.js:2 (flash -> js).log: storeKey=5010755373640022149453736_2.0.7
FileAPI.min.js:2 (flash -> js).log: timeout=0
FileAPI.min.js:2 FlashAPI.state: ready
FileAPI.min.js:2 FlashAPI.event.mouseenter: Object {flashId: "fileapi14238482827122", type: "mouseenter"}
FileAPI.min.js:2 (js -> flash).multiple: false
FileAPI.min.js:2 (flash -> js).log: parseCmd, command: multiple
FileAPI.min.js:2 (js -> flash).accept: *
FileAPI.min.js:2 (flash -> js).log: parseCmd, command: accept
FileAPI.min.js:2 FlashAPI.event.select: Object {flashId: "fileapi14238482827122", type: "select", target: Object}

The file is found, but not passe to the ngModel...

**Comment by danialfarid** [comment]
What version of the plugin? Does the demo page works?

**Comment by danialfarid** [comment]
It could be that you have set `ng-accept` to a value that doesn't match the files you are selecting so the files will be added to `ng-model-rejected="rejectedFiles"`

**Comment by vcharnahrebel** [comment]
It is reproducible on both 3.0.4 and 2.2.2 (angularjs 1.2.15).
ng-accept is not set. I've tried to set it, and check ng-model-rejected, no luck. As noted above, FlashAPI.event.select in logs has appropriate files.
And html5 part works as expected with the same setup.

**Comment by danialfarid** [comment]
Can you reproduce it on the demo page?

**Comment by Johnzero** [comment]
use angular 1.3.0  FileApi 2.0.7 .cant get  files 。please fix this.

**Comment by danialfarid** [comment]
Well if the demo page is working then you need to post your html js here or create a jsfiddle to help figuring out the problem you have in configuring the plugin.

**Comment by Johnzero** [comment]
find a solution:
$scope.usingFlash = window.FileAPI && window.FileAPI.upload != null;
	    if ( (typeof (window.FileAPI) != 'undefined') ) {
	    	var el = document.getElementById('avatar_uploder');
	    	window.FileAPI.event.on(el, 'change', function (evt){
			    var files = window.FileAPI.getFiles(el);
			    $scope.upload(files);
			});
	    }
But get FlashAPI.upload.error 404 error in ie9。
