### ISSUE TITLE
Crossbrowser drag-over-class

### ISSUE THREAD

**Issue by NiekvanderLinden** [danialfarid/angular-file-upload#564]
The rejected and accepted dragover class not working in all browser.
Only seems to work correctly in Chrome. 
In Firefox it only shows the accept class and in Internet Explorer is shows no class.

See this example:
http://jsfiddle.net/9tbr0dog/

**Comment by danialfarid** [comment]
that is mentioned in the readme

**Comment by NiekvanderLinden** [comment]
Yeah, sorry didn't see that.
