### ISSUE TITLE
Drag and drop area shows 'dragover-err' class for csv files

### ISSUE THREAD

**Issue by NilapuAnusha** [danialfarid/angular-file-upload#566]
Hi,

I am using ng-accept="*.csv" for accepting csv file as input but drop area is using 'dragover-err' class instead of 'dragover'. When i am using ng-accept=".csv" then file is not dropping at all.

Could you please suggest me where i am doing mistake?

**Comment by danialfarid** [comment]
`ng-accept="'.cvs'"`

**Comment by NilapuAnusha** [comment]
Thanks @danialfarid, i have already used ng-accept="'.csv'". My problem is 'dragover-err' class added to drop-box instead of 'dragover' when i am dropping csv files.

**Comment by danialfarid** [comment]
Can you create a jsfiddle.

**Comment by anilapu** [comment]
@danialfarid , when ever  I use file extensions like "'.csv, .xlsx'" etc 'dragover' class is not worked but instead of file extensions I used mime type of file like "'text/csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'" then 'dragover' class is worked.

**Comment by danialfarid** [comment]
Fixed in version 3.1.1.
`accept` and `ng-accept` are now acting differently. first one is just for browser filtering, second one is for filtering programmatically.
