### ISSUE TITLE
Dot notation saved twice

### ISSUE THREAD

**Issue by ValentineHypothesis** [danialfarid/angular-file-upload#569]
When using the model directive using dot notation:
.html
ng-file-select ng-model="foo.bar.baz"

.js
var foo = {bar:{baz:[{}]}};

The file is uploaded into two locations, one location is the variable in the js, the other is in a variable that is the string 'foo.bar.baz'. Now if I try to clear the form by setting foo = {bar:{baz:[{}]}} again, the form does not clear, because it is looking at the newly created variable 'foo.bar.baz' rather than at the foo object. This seems like unexpected behavior, it is correctly modeling the file into the created object, and yet it is showing the form based off a non-object variable.

**Comment by danialfarid** [comment]
fixed in version 3.0.5
