### ISSUE TITLE
Attached image thumb preview is not working consistently in IE11

### ISSUE THREAD

**Issue by demisx** [danialfarid/angular-file-upload#570]
You can replicate this issue with your demo page: https://angular-file-upload.appspot.com/

1. Go to https://angular-file-upload.appspot.com/
1. `Click Browse` or `Attach Any File` button
1. Select an image from your drive and click Open
1. The thumb shown. So far, so good.
1. Now, repeat steps 2-4 for other images on your drive. You'll notice that thumbs don't get updated each time you select a new image. Sometimes, they lag behind by one.

**Comment by danialfarid** [comment]
Fixed in version 3.0.7
