### ISSUE TITLE
Safari issues with binding...ng-file-select

### ISSUE THREAD

**Issue by benlooi** [danialfarid/angular-file-upload#571]
Hello.
First of all, thank you for the awesome work.
I have an issue - This is my HTML snippet that is giving me problems.

I have a $scope.album which is an object. 

<label>Album Cover</label>
<label for="album_cover" id='album_cover_label'>Choose File</label>
<input type='file' id='album_cover' onchange='loadFile(event)' ng-file-select ng-model='album.cover'/>

(loadFile event is a function to display the image when chosen.)
When I watch the data-binding in my <pre>, the file is not binding to album.cover in Safari, but it works fine in Chrome.

Also, tried to understand the directive ngFileSelect.  I'm new to Angular, but what is the purpose of the '?' on line 168?

angularFileUpload.directive('ngFileSelect', [ '$parse', '$timeout', '$compile', 
                                              function($parse, $timeout, $compile) { return {
	restrict: 'AEC',
	require:'?ngModel',
	link: function(scope, elem, attr, ngModel) {
		handleFileSelect(scope, elem, attr, ngModel, $parse, $timeout, $compile);
	}
}}]);

How do I get it to work on Safari?

**Comment by danialfarid** [comment]
Could you create a jsfiddle from the example page?
What version of Safari?
It should work on all browsers unless there is a known issue with the browser.

**Comment by benlooi** [comment]
Safari 8.0.2.
Practising the coding on c9.io.  
Is this okay?
https://poompipi-benlooi.c9.io/#/loggedin/addalbum

**Comment by danialfarid** [comment]
The link is working for me on Safari 8.0.3 and OSX 10.10.2

**Comment by benlooi** [comment]
Hmm..worked for me on Android and Chrome. Just my Safari then. Oh well, close this issue then. Thanks Danial!

**Comment by danialfarid** [comment]
It might be a plugin you installed for safari or something
