### ISSUE TITLE
dataTransfer.effectAllowed not supported on IE

### ISSUE THREAD

**Issue by DarkCompiled** [danialfarid/angular-file-upload#572]
You component is not working well on IE 11 (I assume neither works on previous versions).
Its breaking on line 397, because of "evt.dataTransfer.effectAllowed".

Please don't take "dataTransfer.effectAllowed" for granted because it doesn't work on IE.
You may assume it's a "copy" or a "move" operation if you can't determine the operation type.
Please correct this as soon as possible.

Thanks in advance.

**Comment by danialfarid** [comment]
Can you elaborate more what causes it to break?

**Comment by danialfarid** [comment]
fixed in version 3.0.5

**Comment by DarkCompiled** [comment]
Thank you very much! :D
