### ISSUE TITLE
Custom function to extend rejected files

### ISSUE THREAD

**Issue by Spin1987** [danialfarid/angular-file-upload#576]
Thanks for your awesome file upload.
What about a custom function to extend the rejected file upload logic?

I can define "accept" to whitelist file extensions, thats pretty nice. But i cant add a check for files with 0 size. I can do it by my self, but then i have all the 'invalid' files in my files array not in my rejected files array.

```javascript
 $scope.handleFileSelected = function ($files, $rejectedFiles) {
      if ($files && $files.length > 0) {
       // i would like to do this in a fn which add all files in the rejected files.
        var filesWithZeroSize = getFilesWithZeroSize($files);
       }
    }
```

Thank you very much :)

**Comment by danialfarid** [comment]
good idea, gonna add it to the next release

**Comment by danialfarid** [comment]
Added in version 3.1.0
