### ISSUE TITLE
Empty object on Firefox

### ISSUE THREAD

**Issue by bjones2013** [danialfarid/angular-file-upload#577]
When setting the ng-model the array is passed empty objects in Firefox (works fine in Chrome).
I made a jsfiddle (just took your example and added logging) http://jsfiddle.net/uqj2tL1p/2/

Output when ran in Chrome:
 files [
  {
    "webkitRelativePath": "",
    "lastModified": 1422036561000,
    "lastModifiedDate": "2015-01-23T18:09:21.000Z",
    "name": "sample-128.png",
    "type": "image/png",
    "size": 2192
  }

When ran in Firefox:
files [
  {}
]

**Comment by danialfarid** [comment]
That's just `JSON.stringify` that doesn't print the content, if you just `console.log($scope.files[0].name)` you would see that the file is there.

**Comment by deepfriedbrain** [comment]
I noticed a similar thing. But for me even Chrome gives the same result as mentioned for FF above.

**Comment by nikkwong** [comment]
+1

**Comment by danialfarid** [comment]
This is just the browser's console.log implementation
