### ISSUE TITLE
accept=".txt" in dropbox markup does not work

### ISSUE THREAD

**Issue by Caprichoso** [danialfarid/angular-file-upload#582]
I want to let the user only upload *.txt files. Whatever tpye of file I am dragging, there will always be the accept-class (= "dragover") with a green border but NEVER the reject-class (= "dragover-err"). Does anybody see the error?

 <div ng-file-drop ng-file-select ng-model="files" class="drop-box" 
        drag-over-class="dragover" ng-multiple="true" allow-dir="true"
         accept="'.txt'" drag-over-class="{accept:'dragover', reject:'dragover-err', delay:100}">Drop pdfs or images here or click to upload</div>

I adapted the sample fiddle with my dropbox markup:
http://jsfiddle.net/nmdcwf3w/166/

**Comment by danialfarid** [comment]
You have defined drag-over-class twice and only the first one will be considered.
