### ISSUE TITLE
model in ng-model does not get populated

### ISSUE THREAD

**Issue by opengeekv2** [danialfarid/angular-file-upload#583]
The var I'm giving as model to your directive is not getting populated.

```html
<input id="coupon-image" name="img" type="file" ng-model="image">
```
I've been debugging this piece of javascript and it never gets in the if. They are in the same scope but I've already tried with a "dot" model to check if it was a scope prototypal inheritance problem.

```javascript
function uploadImage(coupon) {
  if ($scope.image) {
    var credentials = mtSettings.getOauth2();
    return $upload.upload({
      url: mtSettings.API_BASE_URL + 'coupons' + '/' + coupon.id + '/pic_upload/',
      headers: {'Authorization': credentials.token_type + ' ' + credentials.access_token},
      fileFormDataName: 'img',
      file: $scope.deliverCoupon.image
    });
  } else {
    return coupon;
  }
};
```
Do you see what I could be doing wrong?

**Comment by danialfarid** [comment]
You gotta add `ng-file-select` directive to the element.
