### ISSUE TITLE
Working with Python Flask

### ISSUE THREAD

**Issue by jeffjzx** [danialfarid/angular-file-upload#587]
Hi, i'm new to Web App development and recently trying to upload images using this library. But my attempt fails. Here is my code snippet in order to test the connection of the two:
*HTML*
```<input type="file" ng-file-select="onFileSelect($files)" ng-multiple="false" ng-accept="'image/*'" >```

*JS*
```    
    $scope.onFileSelect = function($files){
            if ($files.length > 0){
            $upload.upload({
                url: '/img_upload/',
                file : $files[0],
                sendObjectsAsJsonBlob: true,
                data: {}
            }).success(function(data, status, headers, config){
                console.log(data);
            });
        }
    };
```
*Python Flask*
```
@app.route('/img_upload/', methods=["POST"])
def upload_img():
	return "test"
```

Here is the request header:
```
Request URL:http://127.0.0.1:5000/img_upload/
Request Headers
Provisional headers are shown
Accept:application/json, text/plain, */*
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryfdwETsFQFZyMqbm8
Origin:http://127.0.0.1:5000
Referer:http://127.0.0.1:5000/
```

Here is the chrome console
``` POST http://127.0.0.1:5000/img_upload/ net::ERR_CONNECTION_RESET```

Since there is too few examples about this library, especially server side with Python, I'm lost quite a while. Hope someone can help, thanks

**Comment by danialfarid** [comment]
So what part is  failing? Can you get `request.files['file']` on the server?

**Comment by jeffjzx** [comment]
Hi, @danialfarid
In my previous snippet, i didn't include  ```request.files['file']``` in my code. But after your suggestion to test if server can receive the file i include this part and the whole thing works. I don't know why this happen, maybe it's a feature of Flask... 
Thanks for replying.
