### ISSUE TITLE
Can't read fields or data

### ISSUE THREAD

**Issue by toksfifo** [danialfarid/angular-file-upload#588]
Uploading the image works perfectly, but I can't seem to pass in any data besides the image itself. 

I'm entering JSON into both "data" and "fields," but I can't retrieve anything from the req on the server. When I `console.log` the req on the server, none of the keys or values passed into "data" or "fields" show up...

**Comment by danialfarid** [comment]
Follow the wiki samples if you are using nodejs on the backend.

**Comment by toksfifo** [comment]
Turns out it was an issue with busboy; thanks.
