### ISSUE TITLE
Cannot set Content-Type for $upload.http()

### ISSUE THREAD

**Issue by MSchmidt** [danialfarid/angular-file-upload#589]
I've tried a bunch of different configuration but setting ``Content-Type`` on ``$upload.http()`` just doesn't do anything. The request gets fired without the header set. However, setting something else like ``X-Content-Type`` for test purposes works well. I know the plugin doesn't do much with the headers but something must cause this behavior. Other regular angular $http requests take the header just fine.

**Comment by danialfarid** [comment]
See the demo page as an example of using `$upload.http()` 
https://github.com/danialfarid/angular-file-upload/blob/master/demo/war/js/upload.js#L97

**Comment by MSchmidt** [comment]
I've tried exactly this last night. Sorry no idea what went wrong. All good now but really don't understand why. Well thanks for the quick reply!
