### ISSUE TITLE
angular-file-upload interferes with hash navigation

### ISSUE THREAD

**Issue by aidanlister** [danialfarid/angular-file-upload#594]
When I add angular-file-upload as a dependency to my module, it starts interfering with my hash navigation. When visiting the url example.com/test/#documents it instantly redirects to example.com/test/#/documents

This seems to have nothing to do with click events, it appears to happen onload.

**Comment by danialfarid** [comment]
That's what angular does. The plugin doesn't do any modification on the window.location or $location.

**Comment by aidanlister** [comment]
I see ... once I add $location as a dependency I see this behaviour. That's not ideal but I'll work it out. Thanks for the response.
