### ISSUE TITLE
ng-multiple not working in 3.1.1

### ISSUE THREAD

**Issue by npearson72** [danialfarid/angular-file-upload#604]
Can someone else confirm?

**Comment by pastme** [comment]
Yes

**Comment by PragmaticIT** [comment]
It seems to be a problem with elem.attributes. Script attached on demo page (https://angular-file-upload.appspot.com/js/angular-file-upload.js) works, but is slightly different than this one in the repo. Difference is in lines 239-241:

working:
		if (attr['multiple']) fileElem.attr('multiple', attr['multiple']);
		if (attr['accept']) fileElem.attr('accept', attr['accept']);
		if (attr['capture']) fileElem.attr('capture', attr['capture']);

not working:
		if (elem.attr['multiple']) fileElem.attr('multiple', elem.attr['multiple']);
		if (elem.attr['accept']) fileElem.attr('accept', elem.attr['accept']);
		if (elem.attr['capture']) fileElem.attr('capture', elem.attr['capture']);

**Comment by gottfrois** [comment]
+1

**Comment by opadillaintegrify** [comment]
+1  I suppose I can just use angular-file-upload.js from the demo, but using the bower version is a nice to have.   Thanks

**Comment by danialfarid** [comment]
Fixed in version 3.1.2

**Comment by npearson72** [comment]
@danialfarid Thanks!
